# Generated by Django 4.1 on 2022-09-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('auther', models.CharField(max_length=100)),
                ('emil', models.EmailField(max_length=200)),
                ('date', models.DateField(max_length=200)),
            ],
        ),
    ]
